(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module fpblind.EdsgerIdents for fpblind.ds *)
Require Import BinPos.  (* positive_scope *)
Require Import backend.AST. (* for ident *)

Definition Bid_struct__blindedBid_ident : ident  := 550%positive.
Definition Bid_struct__deposit_ident : ident  := 551%positive.
Definition Bid_struct_ident : ident  := 552%positive.
Definition Transfer_struct__amount_ident : ident  := 553%positive.
Definition Transfer_struct__to_ident : ident  := 554%positive.
Definition Transfer_struct_ident : ident  := 555%positive.

Definition ident_BlindAuction_auctionEnd : ident  := 556%positive.
Definition ident_BlindAuction_bid : ident  := 557%positive.
Definition ident_BlindAuction_initialize : ident  := 558%positive.
Definition ident_BlindAuction_reveal : ident  := 559%positive.
Definition ident_BlindAuction_withdraw : ident  := 560%positive.
Definition ident_EVMOpcode_transfer : ident  := 561%positive.
Definition var_BlindAuction__beneficiary_ident : ident  := 562%positive.
Definition var_BlindAuction__biddingEnd_ident : ident  := 563%positive.
Definition var_BlindAuction__bids_ident : ident  := 564%positive.
Definition var_BlindAuction__ended_ident : ident  := 565%positive.
Definition var_BlindAuction__highestBid_ident : ident  := 566%positive.
Definition var_BlindAuction__highestBidder_ident : ident  := 567%positive.
Definition var_BlindAuction__pendingReturns_ident : ident  := 568%positive.
Definition var_BlindAuction__revealEnd_ident : ident  := 569%positive.
Definition var_BlindAuction__secrets_ident : ident  := 570%positive.
Definition var_BlindAuction__trueBids_ident : ident  := 571%positive.
