# WARNING: This file is generated by Edsger, the DeepSEA compiler.
#          All modification will be lost when regenerating.
amm_FILES = \
amm/CertiKOS.v \
amm/DataTypeOps.v \
amm/DataTypeProofs.v \
amm/DataTypes.v \
amm/EdsgerIdents.v \
amm/LSimAMM.v \
amm/LSimAMMLIB.v \
amm/LSrcAMM.v \
amm/LSrcAMMLIB.v \
amm/LayerAMM.v \
amm/LayerAMMLIB.v \
amm/ObjAutomatedMarketMakerCode.v \
amm/ObjAutomatedMarketMakerCodeProofs.v \
amm/ObjAutomatedMarketMakerLibCode.v \
amm/ObjAutomatedMarketMakerLibCodeProofs.v \
amm/ObjFixedSupplyToken1Code.v \
amm/ObjFixedSupplyToken1CodeProofs.v \
amm/ObjFixedSupplyTokenCode.v \
amm/ObjFixedSupplyTokenCodeProofs.v \
amm/ObjLiquidityTokenCode.v \
amm/ObjLiquidityTokenCodeProofs.v \
amm/ObjSimAutomatedMarketMaker.v \
amm/ObjSimAutomatedMarketMakerLib.v \
amm/ObjSimFixedSupplyToken.v \
amm/ObjSimFixedSupplyToken1.v \
amm/ObjSimLiquidityToken.v \
amm/RefineAMM.v \
amm/Symbols.v
