# WARNING: This file is generated by Edsger, the DeepSEA compiler.
#          All modification will be lost when regenerating.
token_FILES = \
token/CertiKOS.v \
token/DataTypeOps.v \
token/DataTypeProofs.v \
token/DataTypes.v \
token/EdsgerIdents.v \
token/LSimFIXEDSUPPLYTOKEN.v \
token/LSrcFIXEDSUPPLYTOKEN.v \
token/LayerFIXEDSUPPLYTOKEN.v \
token/ObjFixedSupplyTokenCode.v \
token/ObjFixedSupplyTokenCodeProofs.v \
token/ObjSimFixedSupplyToken.v \
token/Symbols.v
