# WARNING: This file is generated by Edsger, the DeepSEA compiler.
#          All modification will be lost when regenerating.
swaps_threeway_FILES = \
swaps_threeway/CertiKOS.v \
swaps_threeway/DataTypeOps.v \
swaps_threeway/DataTypeProofs.v \
swaps_threeway/DataTypes.v \
swaps_threeway/EdsgerIdents.v \
swaps_threeway/LSimEVMOPCODE.v \
swaps_threeway/LSimSWAPCONTRACT.v \
swaps_threeway/LSrcEVMOPCODE.v \
swaps_threeway/LSrcSWAPCONTRACT.v \
swaps_threeway/LayerEVMOPCODE.v \
swaps_threeway/LayerSWAPCONTRACT.v \
swaps_threeway/ObjSimEVMOpcode.v \
swaps_threeway/ObjSimSwapContract.v \
swaps_threeway/ObjSwapContractCode.v \
swaps_threeway/ObjSwapContractCodeProofs.v \
swaps_threeway/RefineSWAPCONTRACT.v \
swaps_threeway/Symbols.v
