# WARNING: This file is generated by Edsger, the DeepSEA compiler.
#          All modification will be lost when regenerating.
swaps_general_FILES = \
swaps_general/CertiKOS.v \
swaps_general/DataTypeOps.v \
swaps_general/DataTypeProofs.v \
swaps_general/DataTypes.v \
swaps_general/EdsgerIdents.v \
swaps_general/LSimEVMOPCODE.v \
swaps_general/LSimSWAPCONTRACT.v \
swaps_general/LSrcEVMOPCODE.v \
swaps_general/LSrcSWAPCONTRACT.v \
swaps_general/LayerEVMOPCODE.v \
swaps_general/LayerSWAPCONTRACT.v \
swaps_general/ObjSimDiGraph.v \
swaps_general/ObjSimEVMOpcode.v \
swaps_general/ObjSimSwapContract.v \
swaps_general/ObjSwapContractCode.v \
swaps_general/ObjSwapContractCodeProofs.v \
swaps_general/RefineSWAPCONTRACT.v \
swaps_general/Symbols.v
