(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module swaps_general.Symbols for swaps_general.ds *)
Require Import BinPos.
Require Import DeepSpec.Runtime.
Require Import swaps_general.EdsgerIdents.
Require Import String.
Require Import List.
Require Import compcert.common.AST.
Section EdsgerGen.


Open Scope string_scope.

Definition symbols: list (ident * string) :=
  (ident_EVMOpcode_transfer, "EVMOpcode_transfer")::
  (ident_DiGraph_initialize, "DiGraph_initialize")::
  (ident_DiGraph_is_leader, "DiGraph_is_leader")::
  (ident_DiGraph_is_party, "DiGraph_is_party")::
  (ident_DiGraph_is_edge, "DiGraph_is_edge")::
  (ident_DiGraph_get_leader_ind, "DiGraph_get_leader_ind")::
  (ident_DiGraph_get_party_ind, "DiGraph_get_party_ind")::
  (ident_DiGraph_valid_path, "DiGraph_valid_path")::
  (ident_DiGraph_sign_follower, "DiGraph_sign_follower")::
  (ident_DiGraph_sign_leader, "DiGraph_sign_leader")::
  (ident_DiGraph_can_sign_follower, "DiGraph_can_sign_follower")::
  (ident_DiGraph_get_path_len, "DiGraph_get_path_len")::
  (ident_DiGraph_diam, "DiGraph_diam")::
  (ident_DiGraph_maxpathlen, "DiGraph_maxpathlen")::
  (ident_SwapContract_initialize, "SwapContract_initialize")::
  (ident_SwapContract_unlock, "SwapContract_unlock")::
  (ident_SwapContract_claim, "SwapContract_claim")::
  (ident_SwapContract_refund, "SwapContract_refund")::
  (var_SwapContract__assetAmount_ident, "SwapContract__assetAmount")::
  (var_SwapContract__timelocks_ident, "SwapContract__timelocks")::
  (var_SwapContract__hashlocks_ident, "SwapContract__hashlocks")::
  (var_SwapContract__party_ident, "SwapContract__party")::
  (var_SwapContract__counterparty_ident, "SwapContract__counterparty")::
  (var_SwapContract__start_ident, "SwapContract__start")::
  (var_SwapContract__delta_ident, "SwapContract__delta")::
  (var_SwapContract__unlocked_ident, "SwapContract__unlocked")::
  (var_SwapContract__ended_ident, "SwapContract__ended")::
  (var_SwapContract__canrefund_ident, "SwapContract__canrefund")::
  nil.

End EdsgerGen.
