(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module spblind.DataTypes for spblind.ds *)
Require Import BinPos.
Require Import DeepSpec.Runtime.
Require Import spblind.EdsgerIdents.

Section EdsgerGen.


Definition addr := int256.

Record Bid := {
  _blindedBid : hashvalue;
  _deposit : int256
}.

Record Transfer := {
  _amount : int256;
  _to : int256
}.

Definition list_Transfer := (list Transfer).

Definition HASH_Z_Bid := (Int256Tree.t Bid).

Definition HASH_Z_bool := (Int256Tree.t bool).

Definition HASH_Z_Z := (Int256Tree.t int256).

End EdsgerGen.
