(* WARNING: This file is generated by Edsger, the DeepSEA compiler.
            All modification will be lost when regenerating. *)
(* Module spblind.LSrcEVMOPCODE for spblind.ds *)
Require Import BinPos.
Require Import DeepSpec.Runtime.
Require Import spblind.EdsgerIdents.
Require Import spblind.DataTypes.
Require Import spblind.DataTypeOps.
Require Import spblind.DataTypeProofs.


Require Import spblind.LayerEVMOPCODE.

Require Import cclib.Integers.
Require Import cclib.Coqlib.
Require Import cclib.Maps.

Require Import backend.Options.
Require Import backend.AST.
Require Import backend.phase.Clike.Language.
Require Import backend.phase.MiniC.Language.
Require Import backend.Cop.
Require Import backend.Ctypes.
Require Import backend.Compiled.
Require Import backend.Compiled.
Require Import backend.Globalenvs.
Require Import backend.Glue.


Section EdsgerGen.

Definition ge : genv := new_genv (nil)
	nil
	(nil)
	None.


End EdsgerGen.

(*change into extract directory*)
Cd "/Users/sxysun/Desktop/CertiK/DeepSEA/contracts/fpblind/spblind/extraction".

(* Avoid name clashes *)
Extraction Blacklist List String Int.

Separate Extraction
    positive global_abstract_data_type  (* This line forces Coq to generate some files even if they are not used, to make the makefile work correctly. *)
    Glue.full_compile_genv
    ge.
