# WARNING: This file is generated by Edsger, the DeepSEA compiler.
#          All modification will be lost when regenerating.
spblind_FILES = \
spblind/CertiKOS.v \
spblind/DataTypeOps.v \
spblind/DataTypeProofs.v \
spblind/DataTypes.v \
spblind/EdsgerIdents.v \
spblind/LSimBLINDAUCTION.v \
spblind/LSimEVMOPCODE.v \
spblind/LSrcBLINDAUCTION.v \
spblind/LSrcEVMOPCODE.v \
spblind/LayerBLINDAUCTION.v \
spblind/LayerEVMOPCODE.v \
spblind/ObjBlindAuctionCode.v \
spblind/ObjBlindAuctionCodeProofs.v \
spblind/ObjSimBlindAuction.v \
spblind/ObjSimEVMOpcode.v \
spblind/RefineBLINDAUCTION.v \
spblind/Symbols.v
